#=============MAP2B====Fig.S8==============
setwd("C:\\Users\\sunzh\\OneDrive\\×ÀÃæ\\STREAM\\FalsePositives\\Final_format\\supFigs\\Fig3")
modeltest <- read.table("forplot.txt",header = T,sep="\t")
ggplot(modeltest,aes(x=names2,y=accuracy,fill=names2))+geom_boxplot()+theme_bw()+theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))
modeltest <- read.table("forplot.txt",header = T,sep="\t")
ggplot(modeltest,aes(x=Ranks,y=accuracy))+geom_boxplot()+facet_wrap(~classifer)+theme_bw()+theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))
ggplot(modeltest,aes(x=Rank,y=accuracy))+geom_boxplot()+facet_wrap(~classifer)+theme_bw()+theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))
ggplot(modeltest,aes(x=Rank,y=accuracy))+geom_boxplot()+facet_grid(~classifer,scale="free")+theme_bw()+theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))
ggplot(modeltest,aes(x=Rank,y=PR))+geom_boxplot(outlier.colour = NA)+facet_grid(~classifer,scale="free")+theme_bw()+theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))
ggsave("F1score.pdf",width = 12, height = 3)
ggplot(modeltest,aes(x=Rank,y=accuracy))+geom_boxplot(outlier.colour = NA)+facet_grid(~classifer,scale="free")+theme_bw()+theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))
ggsave("Accuracy.pdf",width = 12, height = 3)
modeltest <- read.table("forplot.txt",header = T,sep="\t")
ggplot(modeltest,aes(x=Rank,y=accuracy))+geom_boxplot(outlier.colour = NA)+facet_grid(~classifer,scale="free")+theme_bw()+theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))
ggsave("Accuracy.pdf",width = 12, height = 3)
ggplot(modeltest,aes(x=Rank,y=PR))+geom_boxplot(outlier.colour = NA)+facet_grid(~classifer,scale="free")+theme_bw()+theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1))
ggsave("F1score.pdf",width = 12, height = 3)