channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - perl=5.26.2
  - perl-parallel-forkmanager=2.02
  - python=3.7.0
  - joblib=0.13.2
  - scikit-learn=0.24.1
  - pandas=1.2.0
  - marisa-trie=0.7.7
